server:
  port: 9999

spring:
  threads:
    virtual:
      enabled: true

  application:
    name: SpringAI-Ollama

  datasource:
    url: jdbc:postgresql://192.168.4.10:25432/vitepress_rag
    username: pgvector
    password: pgvector

  ai:
    openai:
      base-url: https://cloud.infini-ai.com/maas

      chat:
        options:
          model: qwq-32b
      embedding:
        options:
          model: bge-m3
      image:
        options:
          model:

    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimension: 1792
        batching-strategy: TOKEN_COUNT # Optional: Controls how documents are batched for embedding
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch


    playground:
      chat:
        models:
          - deepseek-r1
          - deepseek-v3
          - qwq-32b
          - qwen2.5-coder-32b-instruct
          - qwen2.5-vl-72b-instruct